- hosts: all
  roles:
    - run-devstack
    # Run bindep and test-setup after devstack so that they won't interfere
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - test-setup
    - get-os-environment
    - ensure-tox
    - role: tox
      tox_envlist: functional
      tox_install_siblings: false
      environment: "{{ os_env_vars }}"
